#!/usr/bin/env python
"""Fetch real over-the-air RF captures for testing the workbench.

The synthetic captures in ``sample_data/`` are generated by this project, so
they can only prove that the pipeline agrees with itself. These are genuine
SDR recordings made by third parties, published by the PySDR project
(https://pysdr.org) alongside its SDR textbook. They exercise the pipeline on
signals it did not create: a GPS L1 spread-spectrum downlink and an analog
NTSC television transmission.

Usage (Windows PowerShell / cmd / bash)::

    python scripts/fetch_real_data.py            # download every capture
    python scripts/fetch_real_data.py --list     # show the curated sources only
    python scripts/fetch_real_data.py --force    # re-download

Files land in ``real_data/`` (gitignored -- they are large third-party
binaries, not source) together with a ``SOURCES.json`` provenance manifest.
Each download is verified against a pinned SHA-256, so a corrupted or
substituted file is reported instead of silently analysed.

Then analyse them::

    python scripts/run_pipeline.py real_data/gps_l1_4mhz_cf32.iq --sample-rate 4000000 --iq-format auto
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REAL_DATA_DIR = ROOT / "real_data"
TIMEOUT_S = 120

# Verified captures. ``sha256`` pins the exact bytes; update it deliberately if
# the upstream file ever changes.
CAPTURES: tuple[dict, ...] = (
    {
        "name": "gps_l1_4mhz_cf32.iq",
        "url": (
            "https://raw.githubusercontent.com/777arc/PySDR/master/"
            "figure-generating-scripts/GPS_L1_recording_10ms_4MHz_cf32.iq"
        ),
        "size_bytes": 320_000,
        "sample_rate": 4_000_000,
        "iq_format": "complex64",
        "sha256": "76d9e3a3cad57b5d8942603920fef450c74d4b93533321d8367e489fa03a9453",
        "signal": "GPS L1 C/A downlink (spread-spectrum BPSK)",
        "note": (
            "10 ms at 4 MHz. BPSK at 1.023 Mcps with a large carrier offset "
            "that an unlocked capture cannot close -- the pipeline is expected to flag a poor modulation fit."
        ),
    },
    {
        "name": "ntsc_10mhz_cf32.iq",
        "url": (
            "https://raw.githubusercontent.com/777arc/PySDR/master/"
            "figure-generating-scripts/ntsc_remy_10MHz_5925Hz_500ksamples_cf32.iq"
        ),
        "size_bytes": 4_000_000,
        "sample_rate": 10_000_000,
        "iq_format": "complex64",
        "sha256": "8c2333aeadfa5e137d1cc6eea932a193979756e7af8ce41046ada3142481b581",
        "signal": "Analog NTSC television (Remy, 5925 Hz offset)",
        "note": (
            "500k samples at 10 MHz. Analog video is not a digital modulation, "
            "so the tool must refuse to invent a decoded payload. Also the case "
            "that exposed sync-word false alarms on long captures."
        ),
    },
)

MANUAL_GUIDE = """
More real-world RF captures (larger, and useful for a live demo):

  1. SDRangel sample recordings -- NOAA APT weather satellite (137 MHz),
     ADS-B transponders (1090 MHz), AIS ship tracking (162 MHz):
       https://www.sdrangel.org/
  2. Mendeley real-world 2.4 GHz IQ dataset (labelled BPSK/QPSK/QAM/OFDM
     with multipath and line-of-sight captures):
       https://data.mendeley.com/datasets/tjzsbph49x/2
  3. DeepSig RadioML 2016.10A / 2018.01A -- the standard AMC benchmark,
     11 modulation types across -20..+18 dB SNR:
       https://www.deepsig.ai/datasets
  4. IQEngine -- browser for public SigMF recordings with metadata sidecars:
       https://www.iqengine.org/

Drop any downloaded .iq / .wav into real_data/ and analyse it with:
    python scripts/run_pipeline.py real_data/<file> --sample-rate <Hz> --iq-format auto
"""


def _safe_print(text: str) -> None:
    """Print without dying on a cp1252 Windows console."""
    try:
        print(text)
    except UnicodeEncodeError:
        print(text.encode("ascii", "replace").decode("ascii"))


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def download(capture: dict, *, force: bool = False) -> tuple[bool, str]:
    """Fetch one capture. Returns (ok, human-readable detail)."""
    target = REAL_DATA_DIR / capture["name"]

    if target.is_file() and not force:
        actual = sha256_of(target)
        if actual == capture["sha256"]:
            return True, f"already present and verified ({target.stat().st_size} bytes)"
        return (
            False,
            f"present but checksum differs (got {actual[:16]}...) -- use --force",
        )

    try:
        with urllib.request.urlopen(capture["url"], timeout=TIMEOUT_S) as response:
            payload = response.read()
    except (urllib.error.URLError, OSError) as exc:
        return False, f"download failed: {type(exc).__name__}: {exc}"

    if not payload:
        return False, "download returned no data"

    actual = hashlib.sha256(payload).hexdigest()
    if actual != capture["sha256"]:
        return False, (
            f"checksum mismatch -- expected {capture['sha256'][:16]}..., "
            f"got {actual[:16]}...; refusing to write it"
        )

    target.write_bytes(payload)
    return True, f"{len(payload)} bytes, checksum verified"


def write_manifest(results: list[dict]) -> Path:
    manifest = {
        "generated_by": "scripts/fetch_real_data.py",
        "attribution": (
            "Recordings published by the PySDR project (https://pysdr.org) as "
            "companion data for its SDR textbook. Used here as third-party "
            "over-the-air test material."
        ),
        "captures": results,
    }
    path = REAL_DATA_DIR / "SOURCES.json"
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--list", action="store_true", help="print the curated sources and exit"
    )
    parser.add_argument(
        "--force", action="store_true", help="re-download existing files"
    )
    args = parser.parse_args(argv)

    if args.list:
        for capture in CAPTURES:
            _safe_print(f"{capture['name']}")
            _safe_print(f"  signal      : {capture['signal']}")
            _safe_print(f"  sample rate : {capture['sample_rate']} Hz")
            _safe_print(f"  iq format   : {capture['iq_format']}")
            _safe_print(f"  url         : {capture['url']}")
            _safe_print("")
        _safe_print(MANUAL_GUIDE)
        return 0

    REAL_DATA_DIR.mkdir(parents=True, exist_ok=True)
    _safe_print(f"Fetching real over-the-air captures into {REAL_DATA_DIR}\n")

    results: list[dict] = []
    failures = 0
    for capture in CAPTURES:
        ok, detail = download(capture, force=args.force)
        status = "OK  " if ok else "FAIL"
        _safe_print(f"  [{status}] {capture['name']}: {detail}")
        if not ok:
            failures += 1
        results.append({**capture, "downloaded": ok, "detail": detail})

    manifest_path = write_manifest(results)
    _safe_print(f"\nProvenance written to {manifest_path}")
    _safe_print(MANUAL_GUIDE)

    if failures:
        _safe_print(f"\n{failures} capture(s) could not be fetched.")
        return 1
    _safe_print("\nAll real captures fetched and verified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
